import { describe, expect, it } from "vitest";

import { preferInterfaceTypesRule } from "../../src";
import { runRuleCase } from "../support";

describe("prefer-interface-types e2e", () => {
  it("rejects inline object types in parameters and returns", () => {
    // Arrange
    const testCase = {
      code: [
        "function demo(input: { value: string }): { value: string } {",
        "  return input;",
        "}",
      ].join("\n"),
      errors: [
        { messageId: "preferNamedObject" },
        { messageId: "preferNamedObject" },
      ],
      output: [
        "function demo(input: Input): Demo {",
        "  return input;",
        "}",
        "",
        "// TODO: Review this autogenerated type name",
        "interface Input { value: string }",
        "",
        "// TODO: Review this autogenerated type name",
        "interface Demo { value: string }",
        "",
      ].join("\n"),
    };

    // Act
    const result = runRuleCase(
      "prefer-interface-types",
      preferInterfaceTypesRule,
      testCase,
    );

    // Assert
    expect(result.messageIds).toStrictEqual(
      testCase.errors.map((error) => error.messageId),
    );
    expect(result.output).toBe(testCase.output);
  });

  it("autofixes variables and allocates collision-free names", () => {
    // Arrange
    const testCase = {
      code: [
        "interface Item { existing: true }",
        'const item: { id: string } = { id: "1" };',
      ].join("\n"),
      errors: [{ messageId: "preferNamedObject" }],
      output: [
        "interface Item { existing: true }",
        'const item: Item1 = { id: "1" };',
        "",
        "// TODO: Review this autogenerated type name",
        "interface Item1 { id: string }",
        "",
      ].join("\n"),
    };

    // Act
    const result = runRuleCase(
      "prefer-interface-types",
      preferInterfaceTypesRule,
      testCase,
    );

    // Assert
    expect(result.messageIds).toStrictEqual(["preferNamedObject"]);
    expect(result.output).toBe(testCase.output);
  });

  it.each([
    {
      code: [
        "interface DemoInput {",
        "  value: string;",
        "}",
        "",
        "function demo(input: DemoInput): DemoInput {",
        "  return input;",
        "}",
      ].join("\n"),
    },
    {
      code: [
        "type DemoInput = { value: string };",
        "",
        "const demo = (...values: DemoInput[]): DemoInput => values[0]!;",
      ].join("\n"),
    },
  ])("accepts named reusable object types %#", (testCase) => {
    // Arrange
    const ruleName = "prefer-interface-types";

    // Act
    const result = runRuleCase(ruleName, preferInterfaceTypesRule, testCase);

    // Assert
    expect(result.messageIds).toStrictEqual([]);
  });
});
