import type { Rule } from "eslint";

import type {
  FixSourceCode,
  NamedInlineTypeMatch,
  NamingNode,
  RangedNamedInlineTypeMatch,
} from "./types";

const generatedNameTodo = "// TODO: Review this autogenerated type name";

/**
 * Checks whether an AST subtree contains a contextual `this` type.
 * @param value Candidate AST value.
 * @returns Whether moving the value would change `this` semantics.
 * @example
 * ```typescript
 * const contextual = containsContextualThis(typeLiteral);
 * ```
 */
function containsContextualThis(value: unknown): boolean {
  if (Array.isArray(value)) {
    return value.some((item) => containsContextualThis(item));
  }

  if (value === null || typeof value !== "object") {
    return false;
  }

  const node = value as Record<string, unknown>;

  if (node["type"] === "TSThisType" || node["type"] === "ThisExpression") {
    return true;
  }

  return Object.entries(node).some(
    ([key, child]) => key !== "parent" && containsContextualThis(child),
  );
}

/**
 * Checks whether an inner range is fully contained by an outer range.
 * @param outerRange Candidate containing range.
 * @param innerRange Candidate contained range.
 * @returns Whether the inner range is contained by the outer range.
 * @example
 * ```typescript
 * const contained = containsRange([0, 5], [1, 4]);
 * ```
 */
function containsRange(
  outerRange: [number, number],
  innerRange: [number, number],
): boolean {
  return innerRange[0] >= outerRange[0] && innerRange[1] <= outerRange[1];
}

/**
 * Creates the sole aggregate fix for all findings when every source range is safe.
 * @param context Rule execution context.
 * @param matches Named inline object type matches.
 * @returns Aggregate fix callback, or undefined when source data is incomplete.
 * @example
 * ```typescript
 * const fix = createAggregateFix(context, matches);
 * ```
 */
function createAggregateFix(
  context: Rule.RuleContext,
  matches: readonly NamedInlineTypeMatch[],
): ((fixer: Rule.RuleFixer) => Rule.Fix[]) | undefined {
  const sourceCode = getFixSourceCode(context);

  if (
    sourceCode === void 0 ||
    !hasSafeRanges(matches, sourceCode.text.length) ||
    !hasRelocatableMatches(matches, sourceCode)
  ) {
    return void 0;
  }

  const lineEnding = sourceCode.text.includes("\r\n") ? "\r\n" : "\n";
  const declarations = matches
    .map(
      (match) =>
        `${generatedNameTodo}${lineEnding}interface ${match.name} ${sourceCode.getText(match.node as never)}`,
    )
    .join(`${lineEnding}${lineEnding}`);
  const appendText = `${getBlockSeparator(sourceCode.text, lineEnding)}${declarations}${lineEnding}`;

  return (fixer: Rule.RuleFixer): Rule.Fix[] => [
    ...matches.map((match) =>
      fixer.replaceTextRange(match.node.range, match.name),
    ),
    fixer.insertTextAfterRange(
      [sourceCode.text.length, sourceCode.text.length],
      appendText,
    ),
  ];
}

/**
 * Returns the blank-line separator required before the generated block.
 * @param sourceText Existing source text.
 * @param lineEnding Detected source line ending.
 * @returns Separator required before generated declarations.
 * @example
 * ```typescript
 * const separator = getBlockSeparator("const value = 1;", "\n");
 * ```
 */
function getBlockSeparator(sourceText: string, lineEnding: string): string {
  if (sourceText.length === 0 || sourceText.endsWith(lineEnding + lineEnding)) {
    return "";
  }

  return sourceText.endsWith(lineEnding) ? lineEnding : lineEnding + lineEnding;
}

/**
 * Gets the source-code methods only when a complete source payload is available.
 * @param context Rule execution context.
 * @returns Complete source-code payload when available.
 * @example
 * ```typescript
 * const sourceCode = getFixSourceCode(context);
 * ```
 */
function getFixSourceCode(
  context: Rule.RuleContext,
): FixSourceCode | undefined {
  const sourceCode = context.sourceCode as Partial<FixSourceCode> | undefined;

  return sourceCode !== void 0 &&
    typeof sourceCode.text === "string" &&
    typeof sourceCode.getText === "function" &&
    sourceCode.ast !== void 0
    ? (sourceCode as FixSourceCode)
    : void 0;
}

/**
 * Checks whether a literal belongs to a namespace or ambient module.
 * @param node Inline type literal node.
 * @returns Whether EOF insertion would move the declaration outside its module.
 * @example
 * ```typescript
 * const nested = hasModuleAncestor(typeLiteral);
 * ```
 */
function hasModuleAncestor(node: NamedInlineTypeMatch["node"]): boolean {
  let current = (node as NamingNode).parent;

  while (current !== null && current !== void 0) {
    if (current.type === "TSModuleDeclaration") {
      return true;
    }

    current = current.parent;
  }

  return false;
}

/**
 * Checks whether moving every literal to module scope preserves its bindings.
 * @param matches Ranged inline type matches.
 * @param sourceCode Source and scope information for the active file.
 * @returns Whether every literal can safely move to module scope.
 * @example
 * ```typescript
 * const relocatable = hasRelocatableMatches(matches, sourceCode);
 * ```
 */
function hasRelocatableMatches(
  matches: readonly RangedNamedInlineTypeMatch[],
  sourceCode: FixSourceCode,
): boolean {
  const scopes = sourceCode.scopeManager?.scopes;

  if (scopes === void 0) {
    return false;
  }

  for (const match of matches) {
    if (containsContextualThis(match.node) || hasModuleAncestor(match.node)) {
      return false;
    }

    for (const scope of scopes) {
      const references = scope.references ?? [];

      for (const reference of references) {
        const referenceRange = reference.identifier?.range;

        if (
          referenceRange !== void 0 &&
          containsRange(match.node.range, referenceRange) &&
          !isRelocatableReference(match.node.range, reference.resolved?.scope)
        ) {
          return false;
        }
      }
    }
  }

  return true;
}

/**
 * Checks that all replacement ranges exist, are ordered, and do not overlap.
 * @param matches Named inline object type matches.
 * @param sourceLength Existing source length.
 * @returns Whether every replacement range is safe.
 * @example
 * ```typescript
 * const safe = hasSafeRanges(matches, sourceText.length);
 * ```
 */
function hasSafeRanges(
  matches: readonly NamedInlineTypeMatch[],
  sourceLength: number,
): matches is readonly RangedNamedInlineTypeMatch[] {
  let previousEnd = -1;

  const orderedMatches = matches.toSorted(
    (left, right) =>
      (left.node.range?.[0] ?? -1) - (right.node.range?.[0] ?? -1),
  );

  for (const match of orderedMatches) {
    const range = match.node.range;

    if (
      range === void 0 ||
      range[0] < 0 ||
      range[0] < previousEnd ||
      range[1] < range[0] ||
      range[1] > sourceLength
    ) {
      return false;
    }

    previousEnd = range[1];
  }

  return matches.length > 0;
}

/**
 * Determines whether a reference keeps the same binding at module scope.
 * @param literalRange Range of the type literal being moved.
 * @param resolvedScope Scope containing the referenced declaration.
 * @returns Whether the reference is module-safe or moves with the literal.
 * @example
 * ```typescript
 * const relocatable = isRelocatableReference(literalRange, resolvedScope);
 * ```
 */
function isRelocatableReference(
  literalRange: [number, number],
  resolvedScope: import("./types").Scope | undefined,
): boolean {
  if (
    resolvedScope === void 0 ||
    resolvedScope.type === "global" ||
    resolvedScope.type === "module"
  ) {
    return true;
  }

  const scopeRange = resolvedScope.block?.range;

  return scopeRange !== void 0 && containsRange(literalRange, scopeRange);
}

export { createAggregateFix };
