import { describe, expect, it } from "vitest";

import {
  runFix,
  runVerifyAndFix,
} from "./__tests__/prefer-interface-types-autofix-test-helpers";

describe("prefer interface types autofix", () => {
  it("fixes parameter, return, and variable annotations with PascalCase names", () => {
    // Arrange
    const code = [
      'const current_user: { id: string } = { id: "1" };',
      "function parse_value(input_value: { value: string }): { ok: boolean } {",
      "  return { ok: input_value.value.length > 0 };",
      "}",
    ].join("\n");

    // Act
    const actual = runFix(code);

    // Assert
    expect(actual.fixed).toBe(true);
    expect(actual.output).toBe(
      [
        'const current_user: CurrentUser = { id: "1" };',
        "function parse_value(input_value: InputValue): ParseValue {",
        "  return { ok: input_value.value.length > 0 };",
        "}",
        "",
        "// TODO: Review this autogenerated type name",
        "interface CurrentUser { id: string }",
        "",
        "// TODO: Review this autogenerated type name",
        "interface InputValue { value: string }",
        "",
        "// TODO: Review this autogenerated type name",
        "interface ParseValue { ok: boolean }",
        "",
      ].join("\n"),
    );
  });

  it("uses fallback names for destructured parameters and variables", () => {
    // Arrange
    const code = [
      "declare const source: { value: string };",
      "const { value }: { value: string } = source;",
      "const run = ({ value }: { value: string }): { ok: boolean } => ({ ok: !!value });",
    ].join("\n");

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain("const { value }: Type = source;");
    expect(actualOutput).toContain(
      "const run = ({ value }: Parameter): Run =>",
    );
    expect(actualOutput).toContain("interface Type { value: string }");
    expect(actualOutput).toContain("interface Parameter { value: string }");
    expect(actualOutput).toContain("interface Run { ok: boolean }");
  });

  it("uses function, method, and containing variable identifiers for returns", () => {
    // Arrange
    const code = [
      'function load_data(): { value: string } { return { value: "x" }; }',
      "interface Service { fetch_item(): { id: string }; }",
      "const create_entry = function (): { active: boolean } { return { active: true }; };",
      "const build_record = (): { count: number } => ({ count: 1 });",
    ].join("\n");

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain("function load_data(): LoadData");
    expect(actualOutput).toContain("fetch_item(): FetchItem");
    expect(actualOutput).toContain("function (): CreateEntry");
    expect(actualOutput).toContain("(): BuildRecord =>");
  });

  it("avoids top-level and generated-name collisions without deduplicating shapes", () => {
    // Arrange
    const code = [
      'import { Input } from "./input";',
      "interface Input1 { existing: true }",
      "const Input2 = 1;",
      "declare function Input3(): void;",
      "function first(input: { value: string }): void {}",
      "function second(input: { value: string }): void {}",
    ].join("\n");

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain("function first(input: Input4)");
    expect(actualOutput).toContain("function second(input: Input5)");
    expect(actualOutput).toContain("interface Input4 { value: string }");
    expect(actualOutput).toContain("interface Input5 { value: string }");
  });

  it("reports the first wrapped literal per pass and fixes later literals on subsequent passes", () => {
    // Arrange
    const code =
      "function read(value: string | ({ first: boolean }) | { second: boolean }): void {}";

    // Act
    const actual = runVerifyAndFix(code);

    // Assert
    expect(actual.messages).toHaveLength(1);
    expect(actual.fixResult.output).toContain(
      "function read(value: string | (Value) | Value1): void {}",
    );
    expect(actual.fixResult.output).toContain(
      "interface Value { first: boolean }",
    );
    expect(actual.fixResult.output).toContain(
      "interface Value1 { second: boolean }",
    );
  });

  it("attaches one aggregate fix while retaining one diagnostic per literal", () => {
    // Arrange
    const code =
      "function demo(input: { value: string }): { ok: boolean } { return { ok: true }; }";

    // Act
    const actual = runVerifyAndFix(code).messages;

    // Assert
    expect(actual).toHaveLength(2);
    expect(actual.map((message) => message.messageId)).toStrictEqual([
      "preferNamedObject",
      "preferNamedObject",
    ]);
    expect(actual.map((message) => message.fix !== void 0)).toStrictEqual([
      true,
      false,
    ]);
  });

  it("does not move function-scoped generic references to module scope", () => {
    // Arrange
    const code = "function save<T>(input: { value: T }): void {}";

    // Act
    const actual = runVerifyAndFix(code);

    // Assert
    expect(actual.messages).toHaveLength(1);
    expect(actual.messages[0]?.fix).toBeUndefined();
    expect(actual.fixResult.fixed).toBe(false);
    expect(actual.fixResult.output).toBe(code);
  });

  it("does not move namespace declarations or contextual this types", () => {
    // Arrange
    const cases = [
      "namespace Api { export function use(input: { token: string }): void {} }",
      "class Store { update(input: { owner: this }): void {} }",
    ];

    // Act
    const actual = cases.map((code) => runVerifyAndFix(code));

    // Assert
    expect(actual.map((result) => result.messages[0]?.fix)).toStrictEqual([
      void 0,
      void 0,
    ]);
    expect(actual.map((result) => result.fixResult.output)).toStrictEqual(
      cases,
    );
  });

  it("reserves local declarations that could capture generated names", () => {
    // Arrange
    const code = [
      "function outer(): void {",
      "  interface Input { wrong: true }",
      "  function save(input: { value: string }): void {}",
      "}",
    ].join("\n");

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain("function save(input: Input1)");
    expect(actualOutput).toContain("interface Input1 { value: string }");
  });

  it("keeps module-scoped references available to generated interfaces", () => {
    // Arrange
    const code = [
      "interface Token { value: string }",
      "function use(input: { token: Token }): void {}",
    ].join("\n");

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain("function use(input: Input)");
    expect(actualOutput).toContain("interface Input { token: Token }");
  });

  it("preserves CRLF and final-newline separation in generated output", () => {
    // Arrange
    const code = 'const item: { id: string } = { id: "1" };\r\n';

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toBe(
      [
        'const item: Item = { id: "1" };',
        "",
        "// TODO: Review this autogenerated type name",
        "interface Item { id: string }",
        "",
      ].join("\r\n"),
    );
    expect(actualOutput.replaceAll("\r\n", "")).not.toContain("\n");
  });

  it("uses an existing blank line before the generated block", () => {
    // Arrange
    const code = 'const item: { id: string } = { id: "1" };\n\n';

    // Act
    const actualOutput = runFix(code).output;

    // Assert
    expect(actualOutput).toContain(
      ";\n\n// TODO: Review this autogenerated type name\ninterface Item",
    );
    expect(actualOutput).not.toContain(";\n\n\n// TODO");
  });
});
